#!/usr/bin/env python3
"""Extract high-confidence advertising host suffixes from a verified LINE IPA."""
import argparse
from collections.abc import Iterable
from pathlib import Path
import re
import zipfile


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUTPUT = ROOT / 'ad_domains.txt'
HOST_RE = re.compile(
    rb'(?<![A-Za-z0-9_-])'
    rb'((?:[A-Za-z0-9](?:[A-Za-z0-9-]{0,61}[A-Za-z0-9])?\.)+'
    rb'(?:com|net|org|io|me|jp|tv|app|dev))'
    rb'(?![A-Za-z0-9_-])',
    re.IGNORECASE,
)
ASCII_RE = re.compile(rb'[\x20-\x7e]{4,}')
AD_SUFFIXES = (
    'ad.line-scdn.net',
    'admob-gmats.uc.r.appspot.com',
    'doubleclick-cn.net',
    'doubleclick.net',
    'googleadservices.com',
    'googlesyndication.com',
    'imasdk.googleapis.com',
    'taboola.com',
    'taboolanews.com',
)


def is_subdomain(host, suffix):
    return host == suffix or host.endswith('.' + suffix)


def normalized_ad_domain(host):
    host = host.strip('.').lower()
    for suffix in AD_SUFFIXES:
        if is_subdomain(host, suffix):
            return suffix
    return None


def domains_from_blobs(blobs: Iterable[bytes]):
    domains = set()
    for data in blobs:
        for string in ASCII_RE.finditer(data):
            for match in HOST_RE.finditer(string.group()):
                domain = normalized_ad_domain(match.group(1).decode('ascii'))
                if domain:
                    domains.add(domain)
    return tuple(sorted(domains))


def scan_ipa(ipa):
    with zipfile.ZipFile(ipa) as archive:
        members = [
            name for name in archive.namelist()
            if name == 'Payload/LINE.app/LINE'
            or name.startswith('Payload/LINE.app/Frameworks/')
            or name.endswith(('release.json', '.plist', '.json'))
        ]
        return domains_from_blobs(archive.read(name) for name in members if not name.endswith('/'))


def render_domains(domains):
    lines = [
        '# LINE 26.14.0 (2026.828.1845) high-confidence advertising domains.',
        '# Generated by tools/scan_ad_domains.py from the verified IPA.',
        '# Entries match exact hostnames and dot-delimited subdomains.',
        *domains,
        '',
    ]
    return '\n'.join(lines)


def render_header(domains):
    quoted = ',\n    '.join(f'@"{domain}"' for domain in domains)
    return (
        '// Generated by tools/scan_ad_domains.py. Do not edit.\n'
        '#import <Foundation/Foundation.h>\n\n'
        'static NSString * const NEINAdBlockedDomains[] = {\n'
        f'    {quoted},\n'
        '};\n'
        'static const NSUInteger NEINAdBlockedDomainCount = '
        'sizeof(NEINAdBlockedDomains) / sizeof(NEINAdBlockedDomains[0]);\n'
    )


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('input', type=Path, help='Verified source LINE IPA')
    parser.add_argument('output', nargs='?', type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument('--header', type=Path,
                        help='Also write a Foundation header for the injected dylib')
    args = parser.parse_args(argv)
    domains = scan_ipa(args.input)
    if not domains:
        raise ValueError('No recognized advertising domains found.')
    args.output.write_text(render_domains(domains), encoding='utf-8')
    if args.header:
        args.header.write_text(render_header(domains), encoding='utf-8')
    print('\n'.join(domains))


if __name__ == '__main__':
    main()
